class AppStrings {
  static const Map<String, Map<String, String>> strings = {
    // ─── Bottom Navigation ───
    'nav_home': {'th': 'หน้าหลัก', 'en': 'Home'},
    'nav_rent': {'th': 'เช่า', 'en': 'Rent'},
    'nav_post': {'th': 'โพสต์', 'en': 'Post'},
    'nav_chat': {'th': 'แชท', 'en': 'Chat'},
    'nav_profile': {'th': 'โปรไฟล์', 'en': 'Profile'},

    // ─── Home ───
    'home_title': {'th': 'Kaset RentShare', 'en': 'Kaset RentShare'},
    'home_subtitle': {'th': 'เช่าปลอดภัย สำหรับนิสิต มก.', 'en': 'Safe rentals for KU students'},
    'home_search_hint': {'th': 'ค้นหากล้อง, หนังสือ...', 'en': 'Find cameras, textbooks...'},
    'home_post_item': {'th': 'โพสต์สิ่งของ', 'en': 'Post Item'},
    'home_post_item_sub': {'th': 'หารายได้จากของที่มี', 'en': 'Earn from your gear'},
    'home_request': {'th': 'ขอเช่า', 'en': 'Request'},
    'home_request_sub': {'th': 'หาสิ่งที่ต้องการ', 'en': 'Find what you need'},
    'home_categories': {'th': 'หมวดหมู่', 'en': 'Categories'},
    'home_feed': {'th': 'ฟีด', 'en': 'Feed'},
    'home_clear_filter': {'th': 'ล้างตัวกรอง', 'en': 'Clear Filter'},
    'home_no_posts': {'th': 'ยังไม่มีโพสต์', 'en': 'No posts yet'},
    'home_be_first': {'th': 'เป็นคนแรกที่โพสต์หรือขอเช่า!', 'en': 'Be the first to post or request an item!'},
    'looking_to_rent': {'th': 'กำลังหาเช่า', 'en': 'Looking to Rent'},

    // ─── Categories ───
    'cat_all': {'th': 'ทั้งหมด', 'en': 'All'},
    'cat_camera': {'th': 'กล้อง', 'en': 'Camera'},
    'cat_electronics': {'th': 'อิเล็กทรอนิกส์', 'en': 'Electronics'},
    'cat_fashion': {'th': 'แฟชั่น', 'en': 'Fashion'},
    'cat_books': {'th': 'หนังสือ', 'en': 'Books'},

    // ─── Post ───
    'post_title': {'th': 'โพสต์', 'en': 'Post'},
    'post_what_to_do': {'th': 'คุณต้องการทำอะไร?', 'en': 'What would you like to do?'},
    'post_item_title': {'th': 'โพสต์สิ่งของให้เช่า', 'en': 'Post an Item'},
    'post_item_sub': {'th': 'ลงสิ่งของเพื่อให้คนอื่นเช่าแล้วรับรายได้', 'en': 'List your gear for others to rent and start earning'},
    'post_request_title': {'th': 'ขอเช่าสิ่งของ', 'en': 'Request an Item'},
    'post_request_sub': {'th': 'อยากเช่าอะไร? โพสต์แล้วรอเจ้าของมาหาคุณ', 'en': 'Looking to rent something? Post a request and let owners come to you'},

    // ─── Request Details ───
    'request_details': {'th': 'รายละเอียดคำขอ', 'en': 'Request Details'},
    'target_budget': {'th': 'งบประมาณ', 'en': 'Target Budget'},
    'per_day': {'th': '/วัน', 'en': '/day'},
    'start_date': {'th': 'วันเริ่มต้น', 'en': 'Start Date'},
    'end_date': {'th': 'วันสิ้นสุด', 'en': 'End Date'},
    'duration': {'th': 'ระยะเวลา', 'en': 'Duration'},
    'days': {'th': 'วัน', 'en': 'days'},
    'day': {'th': 'วัน', 'en': 'day'},
    'offers': {'th': 'ข้อเสนอ', 'en': 'Offers'},
    'no_offers': {'th': 'ยังไม่มีข้อเสนอ', 'en': 'No offers yet'},
    'make_offer': {'th': 'เสนอสิ่งของ', 'en': 'Make an Offer'},
    'offer_via_chat': {'th': 'เสนอสิ่งของผ่านแชท', 'en': 'Offer via Chat'},
    'offer_form_title': {'th': 'เสนอสิ่งของ...', 'en': 'Make an offer...'},
    'what_you_have': {'th': 'สิ่งของที่คุณมี', 'en': 'What you have'},
    'your_price': {'th': 'ราคาของคุณ (฿/วัน)', 'en': 'Your Price (฿/day)'},
    'condition': {'th': 'สภาพ', 'en': 'Condition'},
    'message': {'th': 'ข้อความ', 'en': 'Message'},
    'submit_offer': {'th': 'ส่งข้อเสนอ', 'en': 'Submit Offer'},
    'submitting': {'th': 'กำลังส่ง...', 'en': 'Submitting...'},
    'offer_success': {'th': 'ส่งข้อเสนอสำเร็จ!', 'en': 'Offer submitted successfully!'},
    'reply': {'th': 'ตอบกลับ', 'en': 'Reply'},
    'offer_price': {'th': 'ราคาเสนอ', 'en': 'OFFER PRICE'},
    'condition_like_new': {'th': 'เหมือนใหม่', 'en': 'Like New'},
    'condition_normal': {'th': 'ปกติ', 'en': 'Normal'},
    'condition_used': {'th': 'มีการใช้งาน', 'en': 'Used'},

    // ─── Chat ───
    'chat_title': {'th': 'แชท', 'en': 'Chats'},
    'no_chats': {'th': 'ยังไม่มีแชท', 'en': 'No chats yet'},
    'no_chats_sub': {'th': 'เริ่มแชทจากรายการเช่าหรือคำขอเช่า', 'en': 'Start a conversation from a rental listing'},
    'type_message': {'th': 'พิมพ์ข้อความ...', 'en': 'Type a message...'},
    'no_messages': {'th': 'ยังไม่มีข้อความ', 'en': 'No messages yet'},
    'start_conversation': {'th': 'เริ่มสนทนาได้เลย!', 'en': 'Start the conversation!'},
    'send_image': {'th': 'ส่งรูปภาพ', 'en': 'Send Image'},
    'create_contract': {'th': 'สร้างสัญญาเช่า', 'en': 'Create Contract'},
    'you_shared': {'th': 'คุณแชร์สิ่งนี้', 'en': 'You shared this'},
    'received_request': {'th': 'ได้รับคำขอเช่าสิ่งนี้', 'en': 'Received a rental request'},
    'view_details': {'th': 'ดูรายละเอียด ›', 'en': 'View Details ›'},
    'you_sent_contract': {'th': 'คุณส่งสัญญาเช่า', 'en': 'You sent a contract'},
    'received_contract': {'th': 'ส่งสัญญาเช่ามาให้คุณ', 'en': 'Sent you a contract'},
    'contract': {'th': 'สัญญาเช่า', 'en': 'Rental Contract'},
    'accepted': {'th': 'ยอมรับแล้ว', 'en': 'Accepted'},
    'declined': {'th': 'ปฏิเสธแล้ว', 'en': 'Declined'},
    'rental_period': {'th': 'ระยะเวลา', 'en': 'Period'},
    'total_price': {'th': 'ค่าเช่ารวม', 'en': 'Total Price'},
    'deposit': {'th': 'ค่ามัดจำ', 'en': 'Deposit'},
    'additional_conditions': {'th': 'เงื่อนไขเพิ่มเติม:', 'en': 'Additional conditions:'},
    'accept': {'th': 'ยอมรับ', 'en': 'Accept'},
    'decline': {'th': 'ปฏิเสธ', 'en': 'Decline'},
    'renting': {'th': 'กำลังเช่า', 'en': 'Renting'},
    'looking_for_rent': {'th': 'กำลังมองหาเช่า', 'en': 'Looking to rent'},
    'budget_label': {'th': 'งบ', 'en': 'Budget'},

    // ─── Request Card (chat message) ───
    'from_request': {'th': 'จากคำขอเช่า', 'en': 'From rental request'},

    // ─── Profile ───
    'profile_title': {'th': 'โปรไฟล์', 'en': 'Profile'},
    'reviews_count': {'th': 'รีวิว', 'en': 'reviews'},
    'get_verified': {'th': 'ยืนยันตัวตน', 'en': 'Get Verified'},
    'total_rentals': {'th': 'เช่าทั้งหมด', 'en': 'Total Rentals'},
    'items_listed': {'th': 'รายการที่ลง', 'en': 'Items Listed'},
    'rental_history': {'th': 'ประวัติการเช่า', 'en': 'Rental History'},
    'edit_profile': {'th': 'แก้ไขโปรไฟล์', 'en': 'Edit Profile'},
    'my_reviews': {'th': 'รีวิวของฉัน', 'en': 'My Reviews'},
    'my_contracts': {'th': 'สัญญาของฉัน', 'en': 'My Contracts'},
    'notifications': {'th': 'การแจ้งเตือน', 'en': 'Notifications'},
    'help_support': {'th': 'ช่วยเหลือ', 'en': 'Help & Support'},
    'about': {'th': 'เกี่ยวกับ', 'en': 'About'},
    'settings': {'th': 'ตั้งค่า', 'en': 'Settings'},
    'logout': {'th': 'ออกจากระบบ', 'en': 'Logout'},
    'logout_confirm': {'th': 'คุณแน่ใจหรือไม่ว่าต้องการออกจากระบบ?', 'en': 'Are you sure you want to logout?'},
    'cancel': {'th': 'ยกเลิก', 'en': 'Cancel'},
    'save': {'th': 'บันทึก', 'en': 'Save'},
    'name_label': {'th': 'ชื่อ-นามสกุล', 'en': 'Full Name'},
    'profile_updated': {'th': 'อัปเดตโปรไฟล์สำเร็จ', 'en': 'Profile updated successfully'},
    'notification_coming_soon': {'th': 'ระบบแจ้งเตือนจะเปิดใช้ได้ในเร็วๆ นี้', 'en': 'Notifications coming soon'},
    'verification_coming_soon': {'th': 'ระบบยืนยันตัวตนจะเปิดใช้ได้ในเร็วๆ นี้', 'en': 'ID verification coming soon!'},

    // ─── Settings ───
    'settings_title': {'th': 'ตั้งค่า', 'en': 'Settings'},
    'language': {'th': 'ภาษา', 'en': 'Language'},
    'language_thai': {'th': 'ไทย', 'en': 'Thai'},
    'language_english': {'th': 'อังกฤษ', 'en': 'English'},
    'notification_settings': {'th': 'การแจ้งเตือน', 'en': 'Notifications'},
    'notification_rental': {'th': 'แจ้งเตือนการเช่า', 'en': 'Rental notifications'},
    'notification_chat': {'th': 'แจ้งเตือนข้อความ', 'en': 'Chat notifications'},
    'app_info': {'th': 'ข้อมูลแอป', 'en': 'App Info'},
    'version': {'th': 'เวอร์ชัน', 'en': 'Version'},

    // ─── Rental History ───
    'rented_out': {'th': 'ให้เช่า', 'en': 'Rented Out'},
    'rented_in': {'th': 'เช่ามา', 'en': 'Rented In'},
    'no_rental_history': {'th': 'ยังไม่มีประวัติการเช่า', 'en': 'No rental history yet'},
    'rented_to': {'th': 'ให้เช่าแก่', 'en': 'Rented to'},
    'rented_from': {'th': 'เช่าจาก', 'en': 'Rented from'},
    'until': {'th': 'ถึงวันที่', 'en': 'Until'},

    // ─── Contracts ───
    'contracts_title': {'th': 'สัญญาเช่า', 'en': 'Contracts'},

    // ─── Reviews ───
    'reviews_title': {'th': 'รีวิว', 'en': 'Reviews'},

    // ─── Help ───
    'help_title': {'th': 'ช่วยเหลือ', 'en': 'Help & Support'},
    'help_contact': {'th': 'ติดต่อผู้ดูแลระบบ:', 'en': 'Contact admin:'},
    'help_hours': {'th': 'เวลาทำการ: จันทร์-ศุกร์ 9:00-17:00 น.', 'en': 'Working hours: Mon-Fri 9:00-17:00'},
    'ok': {'th': 'ตกลง', 'en': 'OK'},

    // ─── Common ───
    'error': {'th': 'เกิดข้อผิดพลาด', 'en': 'Error'},
    'loading': {'th': 'กำลังโหลด...', 'en': 'Loading...'},
    'owner': {'th': 'เจ้าของ', 'en': 'Owner'},
    'requester': {'th': 'ผู้ขอเช่า', 'en': 'Requester'},
    'just_now': {'th': 'เมื่อกี้', 'en': 'Just now'},
    'd_ago': {'th': 'วันที่แล้ว', 'en': 'd ago'},
    'h_ago': {'th': 'ชม.ที่แล้ว', 'en': 'h ago'},
    'm_ago': {'th': 'น.ที่แล้ว', 'en': 'm ago'},
    'coming_soon': {'th': 'เร็วๆ นี้', 'en': 'Coming soon'},

    // ─── Post Rental Screen ───
    'post_rental_title': {'th': 'โพสต์สิ่งของให้เช่า', 'en': 'Post Rental'},
    'add_photos': {'th': 'เพิ่มรูปภาพ', 'en': 'Add Photos'},
    'clear_photos_trust': {'th': 'รูปชัดเจนจะสร้างความเชื่อมั่น', 'en': 'Clear photos increase trust'},
    'item_name': {'th': 'ชื่อสิ่งของ', 'en': 'Item Name'},
    'item_name_hint': {'th': 'เช่น Sony A7III Body', 'en': 'e.g. Sony A7III Camera Body'},
    'item_name_required': {'th': 'กรุณากรอกชื่อสิ่งของ', 'en': 'Please enter item name'},
    'category': {'th': 'หมวดหมู่', 'en': 'Category'},
    'select_category': {'th': 'เลือกหมวดหมู่', 'en': 'Select Category'},
    'select_category_required': {'th': 'กรุณาเลือกหมวดหมู่', 'en': 'Please select a category'},
    'daily_rate': {'th': 'ค่าเช่า/วัน (฿)', 'en': 'Daily Rate (฿)'},
    'deposit_label': {'th': 'ค่ามัดจำ (฿)', 'en': 'Deposit (฿)'},
    'required': {'th': 'กรุณากรอก', 'en': 'Required'},
    'invalid': {'th': 'ไม่ถูกต้อง', 'en': 'Invalid'},
    'desc_and_rules': {'th': 'รายละเอียดและกฎ', 'en': 'Description & Rules'},
    'desc_hint': {'th': 'บอกรายละเอียดของคุณและกฎการดูแล...', 'en': 'Tell renters about your item and any specific rules for care...'},
    'desc_required': {'th': 'กรุณากรอกรายละเอียด', 'en': 'Please enter a description'},
    'post_btn': {'th': 'โพสต์', 'en': 'Post'},
    'max_photos': {'th': 'อัปโหลดได้สูงสุด 5 รูป', 'en': 'Maximum 5 photos allowed'},
    'rental_posted': {'th': 'โพสต์สำเร็จ!', 'en': 'Rental posted successfully!'},
    'condition_label': {'th': 'สภาพสินค้า', 'en': 'Condition'},

    // ─── Post Request Screen ───
    'post_request_appbar': {'th': 'โพสต์คำขอเช่า', 'en': 'Post Request'},
    'what_looking_for': {'th': 'คุณกำลังหาอะไร?', 'en': 'What are you looking for?'},
    'what_looking_hint': {'th': 'เช่น Sony A7III, ชุดครุย', 'en': 'e.g. Sony A7III, Graduation Gown'},
    'describe_need': {'th': 'กรุณาอธิบายสิ่งที่ต้องการ', 'en': 'Please describe what you need'},
    'rental_duration': {'th': 'ระยะเวลาเช่า', 'en': 'Rental Duration'},
    'estimated_budget': {'th': 'งบประมาณ (฿)', 'en': 'Estimated Budget (฿)'},
    'budget_per_day': {'th': 'ราคาต่อวันที่ยินดีจ่าย', 'en': 'Per day price willing to pay'},
    'enter_budget': {'th': 'กรุณากรอกงบประมาณ', 'en': 'Please enter your budget'},
    'invalid_number': {'th': 'ตัวเลขไม่ถูกต้อง', 'en': 'Invalid number'},
    'pickup_location': {'th': 'สถานที่รับของ', 'en': 'Pick-up Location'},
    'set_location': {'th': 'กำหนดสถานที่', 'en': 'Set Location'},
    'select_dates': {'th': 'กรุณาเลือกวันที่เช่า', 'en': 'Please select rental dates'},
    'set_location_required': {'th': 'กรุณากำหนดสถานที่รับของ', 'en': 'Please set pickup location'},
    'location_set': {'th': 'กำหนดสถานที่เป็น มก. บางเขน', 'en': 'Location set to Kasetsart University'},
    'additional_details': {'th': 'รายละเอียดเพิ่มเติม', 'en': 'Additional Details'},
    'additional_details_hint': {'th': 'ระบุสภาพที่ต้องการ, รุ่นที่ต้องการ หรือคำถาม...', 'en': 'Describe the condition you need, specific model requirements, or any questions...'},
    'request_posted': {'th': 'โพสต์คำขอสำเร็จ!', 'en': 'Request posted successfully!'},
    'select': {'th': 'เลือก', 'en': 'Select'},
    'add_photo_at_least': {'th': 'กรุณาเพิ่มรูปอย่างน้อย 1 รูป', 'en': 'Please add at least one photo'},

    // ─── Create Contract Screen ───
    'contract_item_name': {'th': 'ชื่อสิ่งของที่เช่า', 'en': 'Item to Rent'},
    'contract_item_hint': {'th': 'เช่น Sony A7III, ชุดครุย', 'en': 'e.g. Sony A7III, Graduation Gown'},
    'contract_item_required': {'th': 'กรุณาระบุชื่อสิ่งของ', 'en': 'Please enter item name'},
    'contract_select_dates': {'th': 'เลือกวันเริ่ม - วันสิ้นสุด', 'en': 'Select start - end date'},
    'contract_total_price': {'th': 'ค่าเช่ารวม (บาท)', 'en': 'Total Price (฿)'},
    'contract_deposit': {'th': 'ค่ามัดจำ (บาท)', 'en': 'Deposit (฿)'},
    'contract_rules': {'th': 'ข้อตกลงและเงื่อนไข (จุดนัดรับ/สภาพการคืน)', 'en': 'Terms & Conditions (pickup point / return condition)'},
    'contract_rules_hint': {'th': 'เช่น นัดรับหน้า LU คืนในสภาพเดิม ห้ามเปียกน้ำ...', 'en': 'e.g. Meet at LU, return in original condition, keep dry...'},
    'contract_rules_required': {'th': 'กรุณาระบุข้อตกลงเบื้องต้น', 'en': 'Please specify basic terms'},
    'contract_send_btn': {'th': 'ส่งสัญญาเช่า', 'en': 'Send Contract'},
    'contract_sent_msg': {'th': 'ส่งสัญญาเช่า', 'en': 'Sent rental contract'},
    'numbers_only': {'th': 'ตัวเลขเท่านั้น', 'en': 'Numbers only'},

    // ─── Category Names ───
    'cat_sports': {'th': 'กีฬา', 'en': 'Sports'},
    'cat_music': {'th': 'ดนตรี', 'en': 'Music'},
    'cat_tech': {'th': 'เทคโนโลยี', 'en': 'Tech'},
    'cat_others': {'th': 'อื่นๆ', 'en': 'Others'},
  };
}
